services:
  app-elasticsearch:
    container_name: stac-fastapi-es
    image: stac-fastapi-elasticsearch-opensearch-app-elasticsearch
    environment:
      - STAC_FASTAPI_TITLE=stac-fastapi-elasticsearch
      - STAC_FASTAPI_DESCRIPTION=A STAC FastAPI with an Elasticsearch backend
      - STAC_FASTAPI_VERSION=6.0.0
      - STAC_FASTAPI_LANDING_PAGE_ID=stac-fastapi-elasticsearch
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - RELOAD=true
      - ENVIRONMENT=local
      - WEB_CONCURRENCY=10
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - ES_USE_SSL=false
      - ES_VERIFY_CERTS=false
      - BACKEND=elasticsearch
      - DATABASE_REFRESH=true
      - ENABLE_COLLECTIONS_SEARCH_ROUTE=true
      - REDIS_ENABLE=false
    ports:
      - "11622:8080"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
      - ./esdata:/usr/share/elasticsearch/data
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-8.11.0}
    hostname: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx1g
      action.destructive_requires_name: false
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
    ports:
      - "9200:9200"

  stac-browser:
    container_name: stac-browser
    image: ghcr.io/radiantearth/stac-browser:latest
    ports:
      - 11624:8080
    environment:
      SB_catalogUrl: "http://140.208.147.13:11622"
